final-form/final-form

README.md
I had to check the source code after reading the readme to check that `intialValues` did also do the obvious thing of setting initial values.  The readme made it sound like they were only used for pristine/dirty checks.
=> Make it clear that initialValues is used as the initial form data, not just for pristine/dirty

package-scripts.js, src/index.d.ts
I manually translated the Flow typings to TypeScript typings.
The conversion was largely obvious, apart from `FormApi.submit` and `Config.onSubmit`, where I'm not sure whether all the `undefined`s are wanted; I think they're a correct literal translation, but might not be the intention.
=> Add TypeScript typings

src/index.d.ts
When a developer wants to reuse types, one cannot pick from or extend any `type`, but can from any `interface`.
This PR is neutral in typing results but provides a better case for reuse/extension of types in a developer's application.
I'll be submitting a similar PR for react-final-form shortly.
=> [typescript] Use interfaces where possible for reuse cases

package-lock.json, package-scripts.js, package.json, src/index.d.test.ts, src/index.d.ts, tsconfig.json, tslint.json
Supersedes #60 
Based on the conversation in #60, I have continued @brikou's work and expanded the test case.  
- I did a runtime capture of state and added these assertions in the test.
- I broke out the indexer signature as `AnyObject` for easier referencing/testing
- I changed optionality of many members as provided instead of optional, as by default they are populated.  
- I addressed my concerns about `Partial` and made sure @brikou's original tests run.
While it's likely not perfect, I think this is an improvement and more accurate representation of types by default.  Here's the screen capture of values I used for `FormState`.
Thanks to @brikou for getting this started.
=> Typescript tests and fixes

package.json, src/FinalForm.js, src/index.d.test.ts, src/index.d.ts, src/types.js.flow
I have peeled all layers of the onion.  This is the first domino that needs to fall.
Strongly typed users when attempting to use `mutators` in a form render will have to cast as it may be `undefined`.  This can be a painful and likely unnecessary experience.  This simple change will bring joy and sunshine to the lives of typescript developers far and wide.
https://github.com/final-form/react-final-form/pull/129 depends on this, as do PRs in the arrays projects.
@erikras please review this one first.
=> Ensure `mutators` is defined to avoid bad strongly typed developer casting experienc

README.md, src/FinalForm.js, src/FinalForm.validating.test.js, src/types.js.flow
Allows automatic validation to be paused and resumed. Allows fix for #73.
=> Added pause/resume validation functions

README.md, package-lock.json, package.json, src/FinalForm.js, src/FinalForm.submission.test.js
=> Reset submit state when form.reset() is called

src/FinalForm.js, src/FinalForm.setConfig.test.js, src/index.d.ts, src/types.js.flow
[see final-form/react-final-form#128]
This method lets you update any of the config values after the initial form creation. Updating mutators might be a bit slow, so would be best avoided, but all the other config options should be fine to update.  This will make it fairly simple to fix the issue in react-final-form where props can get out of date.
=> Add method for setting config value after form creation

README.md, src/FinalForm.js, src/FinalForm.validating.test.js, src/index.d.ts, src/index.js, src/publishFieldState.js
You can now set an error for an array of fields.
```jsx
import { ARRAY_ERROR } from 'final-form'
...
errors.items = []
errors.items[ARRAY_ERROR] = 'You need some items'
```
=> Added a way to set an error on an array of fields

README.md
Hi!
It seems that the documentation in REAMDE.md for DebugFunction was in the wrong place. This PR moves it and also fixes the wording - "returns" => "receives".
=> Fix the API doc for DebugFunction in README.md

.babelrc, rollup.config.js
size comparison:
before - 4419
after - 4242
Usually savings are bigger, I guess u dont use that much of es6 that needs heavier babel transforms.
=> Use babel loose mode

src/structure/getIn.js
Kinda related to #106. Transpiled for-of depends on `Symbol`
Not only this makes it symbol-independent, it makes also the overall output a little bit smaller:
before - 4419
after - 4336 💵
=> Prefer simple for loop over for-of (it doesnt have to be transpiled)

README.md, src/FinalForm.js, src/FinalForm.setConfig.test.js, src/index.d.ts, src/index.js, src/index.js.flow, src/types.js.flow
Fixes https://github.com/final-form/react-final-form/issues/246.
Mimics the behavior of [`keepDirtyOnReinitialize`](https://redux-form.com/7.3.0/docs/api/reduxform.md/#-code-keepdirtyonreinitialize-boolean-code-optional-) from Redux Form.
=> Added keepDirtyOnReinitialize config flag

src/FinalForm.js, src/FinalForm.mutators.test.js, src/FinalForm.subscribing.test.js
Fixes https://github.com/final-form/final-form-calculate/issues/15.
Fixes https://github.com/final-form/final-form/issues/102.
I have been thinking about why I originally chose to not allow changes to non-registered fields, and I cannot defend the decision. It makes the library less flexible. This PR lets you now modify field values for fields that are not currently registered.
=> Allow form.change() to set values for non-registered fields

src/index.d.ts, src/types.js.flow
I noticed a handful of fields missing from the TypeScript declaration, so I updated it to match the Flow one.
In regards to TS, the type `object` isn't ideal, as it doesn't support nested objects correctly. It really needs to be something like `AnyObject`. Furthermore, I would highly suggest typing data/errors/other objects, for example:
```
export interface Data {
[key: string]: any;
}
export interface Errors {
[key: string]: string;
}
```
Seems like a bigger task, as Flow would need it to, so I opted not to do it.
=> Fix/improve TS declaration

src/FinalForm.creation.test.js, src/FinalForm.js
Added a check to make sure a field is registered when inspecting its `validationFields` property.
Fixes https://github.com/final-form/react-final-form/issues/278.
=> Fixed validation bug when changing unregistered field

src/FinalForm.js
When calling form.reset currently the code resets the submitErrors value but not the submitError value despite setting both when submitting.
=> Updated reset to delete submitError

src/FinalForm.js, src/index.d.ts, src/types.js.flow
Fix for #124 
*Important*: Work in progress, opened the PR after spiking through `final-form`, so we can discuss and agree on a final and more refined solution.
Pass the field metadata as a third argument to any validator function, enabling validators to also consider the field state (active, dirty, touched, etc...) while validating.
This is specially useful in cases where there is a validator composition since some validations require more context than the value.
Example: imagine an `edit` form sharing the same validations as the `create` form, in this form a `unique` validation for a previously filled field should only check for uniqueness if the value has changed. Validating if it hasn't changed will always fail the validation, and there's no way to tell today since there's no way to …
=> feature: Include field metadata as argument to field validators

package.json
`prepublish` runs when doing local `npm install`, `prepare` runs before publishing - seems to me like a better fit here
=> Change prepublish script to prepare

src/index.d.test.ts, src/index.d.ts
`createForm` now have a type parameter.
Sorry for the reformatting on `src/index.d.test.ts`, but it was caused by the precommit hook
=> Add TypeScript typings to form data values

README.md, src/FinalForm.js, src/index.d.ts, src/types.js.flow
Usage:
```
initialize((values) => ({ ...values, any: null }))
```
=> accept function as argument in initialize()

src/structure/setIn.js
`Object.keys` is called only when necessary.
I go from 3.57s to 2.93s by making a change on a huge form. (related to https://github.com/final-form/final-form/issues/193)
The remaining slow part is:
https://github.com/final-form/final-form/blob/f02fd2699e4cb056b9d55882c1ac0d80e77ef9e7/src/structure/setIn.js#L66-L69
=> improve performance of setIn

package-lock.json, src/index.d.test.ts, src/index.d.ts
We have been using Final Form in a React project for about a year now. It's been overall great, but the lack of valid types around form data has been a bit annoying. 
For example:
```tsx
<Form
initialValues={{ name: "Billy" }}
onSubmit={formData => {
console.log(formData.name) // Error
}}
validate={formData => {
console.log(formData.name) // Error
}}
>
...
</Form>
```
This PR contains some initial changes to the definitions required to improve the situation. A subsequent PR to react-final-form will be necessary to solve the problem entirely. I would like to eventually take the `react-apollo-hooks` approach and use no-op inheritance to do this:
```tsx
class PersonForm extends Form<{ name: string }> {}
<PersonForm
initialValues={{ name: "Billy" }}
onSubmit={formData => { …
```
=> Improvements to the Typescript types around FormData

src/FinalForm.js
When final form notifies form listeners on `complete`, it can happen that notifying one subscriber will cause another subscriber to unsubscribe, effectively removing the entry from the iterated list.
The [following example](https://codesandbox.io/s/zwqxoz8nn3) shows how it can throw:
```
final-form.cjs.js:404 Uncaught (in promise) TypeError: Cannot read property 'subscription' of undefined
at eval (VM20664 final-form.cjs.js:404)
at Array.forEach (<anonymous>)
at notify (VM20664 final-form.cjs.js:402)
at notifyFormListeners (VM20664 final-form.cjs.js:824)
at complete (VM20664 final-form.cjs.js:1179)
```
The PR adds a guard to prevent the error.
Fixes https://github.com/final-form/react-final-form/issues/159
=> guard against deleted entry in notify

src/FinalForm.js, src/FinalForm.subscribing.test.js, src/filterFormState.js, src/index.d.test.ts, src/index.d.ts, src/index.js.flow, src/publishFieldState.js, src/types.js.flow, tslint.json
People have been attempting to get close to this for a while now.
It's my understanding that there's no good way of typing the actual fields. What this provides is strong typing for the `values` and `initialValues` when using Final Form.
=>  Strongly typed form values for Flow and Typescript

package.json, src/FinalForm.js, src/FinalForm.validating.test.js, src/fieldSubscriptionItems.js, src/publishFieldState.js, src/types.js.flow
Sometimes when uploading files directly from input on change, instead of on submit, in that case that Field needs to provide a key like ```validating``` equals to true  till promise resolves, to show loader.
Every Field providing ```subscribeToEachFieldsPromise``` equals to true will receive notification every time validate function's promise is resolves.
=> Added a validating key  to fieldState, will be true when promise returned from a field validate function,useful for individual file uploads in form.

README.md, package.json, src/FinalForm.js, src/FinalForm.validating.test.js, src/index.d.ts, src/publishFieldState.js, src/types.js.flow
Reimplements #232 keeping `validating` state directly in `InternalFieldState`.
=> Field validating flag

README.md, src/FinalForm.creation.test.js, src/FinalForm.js, src/index.d.ts, src/types.js.flow
This change would allow `form.registerField` to initialize the `data` property for the field being registered, like `initialValue`, `defaultValue`, etc. I implemented this in response to seeing #240. Hopefully I've covered all my bases.
=> Added data to FieldConfig

package.json, src/FinalForm.js, src/index.d.ts, src/types.js.flow
Mutators can now mark a field as `forceUpdate` to ensure that its subscribers will be notified.
=> Added internal forceUpdate flag for fields for final-form-arrays' mutators

.gitignore, README.md, package.json, src/FinalForm.js, src/FinalForm.subscribing.test.js, src/index.d.ts, src/types.js.flow
Reverts #244.
Added new `resetFieldState` API to allow field flags to be cleared. This is all part of fixing `final-form-arrays` bugs, e.g. https://github.com/final-form/final-form-arrays/issues/18.
=> Removed forceUpdate, added resetFieldState API

src/FinalForm.js, src/FinalForm.validating.test.js
This PR introduces `Rx#switchMap`-like behavior into final-form async record- and field-level validations using the existing `nextAsyncValidationKey` logic, and applying it to the set of validations rather than individual validations. Then, when an async validation is resolved, we determine whether or not it is the most recent validation, ignoring it otherwise.
see https://github.com/final-form/final-form/issues/147#issuecomment-519881470 for discussion, but the gist is that when validation takes a conditionally long time to return, old values can take longer than new values (especially if your validation hits a server only _after_ sync validation passes) and we can enter invalid states when the old validation results overwrite the state after the latest validation result has already …
=> feat: ignore old async-validation results

src/FinalForm.debugging.test.js, src/FinalForm.fieldSubscribing.test.js, src/FinalForm.js, src/FinalForm.setConfig.test.js, src/FinalForm.subscribing.test.js, src/FinalForm.validating.test.js
Record level validation was getting called on every field registration. No reason for that unless the field registered a field-level validator.
=> No need to run validation on field register without validator

src/FinalForm.batching.test.js, src/FinalForm.js
By turning inBatch from a flag to a semaphore.
=> FinalForm.js: Allow nested batch() calls

src/index.d.test.ts, src/index.d.ts
Hello, Eric (and whoever checks this tiny PR)!
I've found a small inconsistency in TypeScript type definitions: custom type of mutator is not passed down to it in the `Config` interface, which leads to use of the default placeholder type (which is `object` currently, you can see it on line 256). This PR fixes this small issue and updates the appropriate unit test.
Thank you for a great job around Final Form! 👍
=> Fixed config typing for mutators

docs/types/FieldConfig.md, src/FinalForm.creation.test.js, src/FinalForm.js
PR for a potential solution for issue [#387](https://github.com/final-form/react-final-form/issues/387)
Set `defaultValue` if:
- `defaultValue` in `<Field/>` is not `undefined`
- `initialValue` in `<Field/>` is undefined
- value from `initialValues` in form `Config` is `undefined`
=> Use defaultValue when initialValue(s) is undefined

README.md
This used to link to a note added in #180:
>  Technically there is a dependency on `@babel/runtime`, but [this actually makes your final bundle size _smaller_ by sharing common babel code between libraries](https://babeljs.io/docs/en/babel-runtime#why).
=> docs(README): remove broken link

docs/companion-libraries.md
Data Driven Forms is a library which takes JSON schema and changes it into full React components, with all features provided. It would be cool to have it mentioned here.
=> Add Data Driven Forms to the list of libraries

package.json, src/FinalForm.js, src/FinalForm.setConfig.test.js
When keepDirtyOnReinitialize is not set, all non-registered values go to `form.values`, which is useful for computed values depending on such non-registered values. Replicate the same behavior when keepDirtyOnReinitialize is set as well.
=> Reinitialize non-registered values with keepDirtyOnReinitialize

src/FinalForm.js, src/FinalForm.submission.test.js
Fix issue #308 by aborting the submit on async validation error.
=> stop resubmitting when validator throw an error and log the error instead

src/FinalForm.js, src/FinalForm.validating.test.js
fixes #296
When a field was registered with `initialValue`, form validation was never run on that value and therefore form remained invalid.
This pr changes to run form validation on field register when there's an initial value.
=> Fix field initial value validation

.travis.yml
They dont build anyway because you are using `lint-staged` version that has dropped support for nodes older than 10~. Alternatively `lint-staged` could be moved out of `"prepare"` script.
=> Remove node 8 & 9 from testes environments on Travis

package.json, src/structure/toPath.js
Hi,
We have some performance issue with big form (more thousand field) and we find that `toPath` method take a long time. As it is a pure fonction, by caching results, we get a significant improvement.
What do you think about this optimisation ?
Thanks in advance.
=> Optimize toPath method by caching results

docs/getting-started.md, package-lock.json, package.json
This change adds a dependency on scarf-js for installation analytics to support the maintainers of Final Form.
Discussion from everyone is welcome! Some background on the library and the problem it's solving can be found in this post here: https://github.com/scarf-sh/scarf-js/blob/master/WHY.org. The package README (https://github.com/scarf-sh/scarf-js) has more info on exactly what data is sent on each install and how users can opt-out if they choose.
The data Scarf collects will help maintainers by keeping them informed about how the package is being used and will help drive sponsorship to support all the work that goes into Final Form.
=> Add scarf-js for anonymized installation analytics

src/FinalForm.js, src/FinalForm.validating.test.js
This pull request fixes a problem I noticed while working with an async field level validator, which is wrapped in a debounce function. The third argument was missing:
```
const validate = pDebounce(async (value, allValues, meta) => {
console.log(meta); // undefined
}, 500);
```
After investigating the problem I found that `pDebounce` calls my function with a spread operator to pass on arguments: `func(...arguments)`. The function it returns has 0 (unknown) number of arguments and so `validate.length` would give us 0. This is a typical behaviour of a high order function.
In my fix I suggest to pass all three arguments to a 0 argument validator function. `validator.length === 0` would indicate unknown number args of a given function and so won't skip `fieldState`.
=> Fix missing FieldState argument if validator function is wrapped

src/index.d.ts
fixes #314
Add a new type, InitialFormValues
We could also default to FormValues if you prefer to avoid potential typescript definition breakings ?
=> Add InitialValues type default to Partial<FormValues>

docs/getting-started.md, package-lock.json, package.json
Removes scarf dep and also performs `npm audit fix`. For now, FF has received many benefits from Scarf, but until it shows more, we don't need analytics for everyone that installs the library.
Fixes https://github.com/final-form/react-final-form/issues/822
=> Remove scarf dep

docs/types/FormApi.md, src/index.d.ts
Hey,
I think the argument for form.reset should be `InitialFormValues` instead of `FormValues`.
Cheers
=> Fix form.reset type

src/index.d.ts
Both `FormState.errors/submitErrors` properties can be `undefined` if there is no errors.
This moves the nullable to the type aliases so they are not missed in some places.
=> [types] Fix FormState.errors/submitErrors is nullable

src/FinalForm.js, src/FinalForm.submission.test.js
Closes https://github.com/final-form/final-form/issues/362, related to https://github.com/final-form/final-form/pull/229.
=> Fix reset in onSubmit

src/FinalForm.js, src/FinalForm.validating.test.js
I've discovered an issue where by the field-level async validation isn't updating the `validating` to false once the promise resolves after the field is blurred.
See screenshot of reproduced error
Steps
1. Vist the async field example https://codesandbox.io/s/wy7z7q5zx5
2. Type `john` in the username field and blur the field immediately
3. `validating` never gets set to `false
`runFieldLevelValidation` is being passed a reference the `field` state which the blur event is overriding. This means that the promise's clousure will have a stale `field` reference.
This PR changes the `runFieldLevelValidation` to receive the field name and relies on references to `state.fields[name]`
PR adds test coverage as well.
I've had some trouble with the precommit hook on master. I've tried to ensure it …
=> Fix validating field state when blurring before the promise is resolved

src/FinalForm.js
Issue:
1. Form state has value for a field
2. Calling `register` for that field name with `defaultValue` ignores the fact that form state already has a value and changes it to the default value
It seems that the same check as for `initialValue` should be used for `defaultValue` usage in `register` call.
Let me know if I'm missing something in the logic of the `register` call.
=> Do not use defaultValue in register call if formState already has a value

src/FinalForm.js
It's related to final-form/react-final-form#823.
I see #364 tried to solve this issue above, but unfortunately it conflicts with #372. 
With both pull request merged, FinalForm (as of `4.20.2`) still require a field to have “noValueInFormState” before it can apply its field-level `initialValue`.
https://github.com/final-form/final-form/blob/0d7aecbc37c140610361506781fe839b85302836/src/FinalForm.js#L860-L866
This PR tries to restore the original purpose of #364 by removing `&& noValueInFormState` requirement from the expression.
=> Fix field-level initialValue should not be blocked by noValueInFormState

LICENSE, src/structure/toPath.js, src/structure/toPath.test.js
fix #380
Since doing this right is non-trivial, I copied over the code from lodash' `stringToPath` and appended lodash' license to the `LICENSE`.
Although we could use the `lodash.topath`, [those modular build packages are discouraged and will be removed in v5](https://github.com/lodash/lodash/issues/3838#issuecomment-398592530).
The better alternative, really, is just to depend on `lodash` and import `toPath` from it.  People are averse to transitive deps but only the code `toPath` depends on would get bundled, and that code could be shared with any other packages/userland code that rely on `toPath`, so it can result in smaller overall bundle sizes than duplicating the code or using the `lodash.topath` modular build package.
=> fix(toPath): handle idiomatic JS paths with arbitrary string properties

package.json, src/FinalForm.js, src/FinalForm.submission.test.js
We noticed that the modifiedAfterSubmit property doesn't seem to get reset when there are errors. This is a slight behaviour change, but we believe this would be the correct behaviour. I've added a test case to prove the bug as well.
- modifiedAfterSubmit property not being reset when there are errors
=> Fix modifiedAfterSubmit property not being reset when there are errors

package.json, src/FinalForm.js, src/FinalForm.validating.test.js, src/types.js.flow
Bug demonstrated here: [CodeSandbox](https://codesandbox.io/s/beautiful-glitter-5mxo4?file=/src/App.tsx)
With this change, we remember the previous async errors, and only clear them when the async validation has returned.
=> Don't clear async errors between validations

docs/types/FormApi.md
Fix `form.restart` method definition on the docs
=> DOCS: Fix restart method definition

src/FinalForm.js
Resolve https://github.com/final-form/final-form/issues/449
The root of the problem is `setIn` returns undefined if you pass in an undefined `value`. I assume this is intentional so I just added the `|| {}` to ensure that `form.values` can never be undefined.
=> Prevent formState.values from initializing to undefined

package.json, src/FinalForm.js, src/FinalForm.registerField.test.js
If mutator creates a new field in `MutableState` for keeping the field state of a renamed field, set the `blur`, `focus` and `change` function of `InternalFieldState` when `registerField` is called.
This is needed by react-final-form-array because of this sequence of events as shown in https://github.com/final-form/final-form-arrays/issues/58
- FieldArray registers foo
- Field registers foo[0].a
- Field registers foo[1].b
- call `remove` mutator to remove foo[0]
- in order to keep field states (touched, visited etc), `remove` mutator copies the field foo[1].b to foo[0].b. Note that there isn't any input fields subscribed to foo[0].b
- FieldArray unmounts Field foo[1].b
- Field foo[0].a gets re-rendered, runs the useEffect clean up on foo[0].a and registers foo[0].b
Before this pull …
=> Set blur, focus and change in InternalFieldState when registerField is called.

src/structure/toPath.js, src/structure/toPath.test.js
**Fix for issue #456 - Fixes unwanted breaking change for array input names introduced in v4.20.3 (a3575ef0c51277ab253e58fbb580de11de73f101) - v4.20.2 used to work fine**
Hello @erikras and @jedwards1211,
Commit a3575ef0c51277ab253e58fbb580de11de73f101 ([PR 381](https://github.com/final-form/final-form/pull/381)) introduced a breaking change for array input names like `choices[]` and `options[]` (see issue #456).
In v4.20.2, keys like `"choices[]"` and `"options[]"` all map to the following correct paths: `["choices"]`, `["options"]`.
Since v4.20.3, after [PR 381](https://github.com/final-form/final-form/pull/381) was merged, `"choices[]"` and `"options[]"`
started to map to `["choices", ""]` and `["options", ""]`, which is not retro-compatible with what we had in v4.20.2 and breaks some …
=> Fix for issue #456 - Fixes unwanted breaking change for array input names

package-scripts.js, src/FinalForm.fieldSubscribing.test.js, src/FinalForm.js
Fix the issue #411.
Affects also the issue commented in react final form: https://github.com/final-form/react-final-form/pull/932
The problem occurs when you register a field with silent to true and with an async validator and immediately unregister it.
This is exactly what is done in React Final Form in the Field component.
The field validator, being asynchronous, terminates when the field no longer exists in the form and calls the `notifyFieldListeners` for that field.
I have changed the code so that once the validation finishes if it is `silent=true` it checks if the field still exists.
Also, in order to reproduce the bug in node before V16, I had to add the option `NODE_OPTIONS=--unhandled-rejections=strict` in the package-scripts.js
Cheers!
=> fix #411: unsuscribe field before the validation finish throw unhandled rejections exception in node 16

src/index.d.ts
I don't understand the reason why 2nd argument became optional in typings (#394), it is always being passed. Upgrading from `4.20.6` to `4.20.7` breaks the TS code.
What about to revert this change?
=> Revert validator `allValues` optional argument

src/FinalForm.js
try fix https://github.com/final-form/react-final-form/issues/780
=> fix: async validating
