src/types.js.flow
Ref: https://github.com/facebook/flow/pull/5251/files#diff-453a8ac419736c97694ea5b93d1965e0R120
=> Use $Shape<T> instead of optional fields

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, LICENSE
Ref: https://github.com/erikras/final-form/community
=> Meet the GitHub community standards

README.md
=> Bring API docs in line with real API

README.md, package.json, src/FinalForm.fieldSubscribing.test.js, src/FinalForm.js, src/FinalForm.mutators.test.js, src/fieldSubscriptionItems.js, src/filterFieldState.js, src/filterFieldState.test.js, src/filterFormState.js, src/index.js.flow, src/publishFieldState.js, src/publishFieldState.test.js, src/shallowEqual.js, src/structure/getIn.js, src/structure/setIn.js, src/subscriptionFilter.js, src/types.js.flow
Support for third party functions to mutate internal form state.
=> Mutators!!

src/FinalForm.fieldSubscribing.test.js, src/FinalForm.js, src/FinalForm.subscribing.test.js
Fixes https://github.com/erikras/react-final-form/issues/22.
=>  Allow a field to be touched even if it wasn't active

src/FinalForm.js, src/FinalForm.submission.test.js
Fixes https://github.com/erikras/react-final-form/issues/17.
=> Fixed bug in sync error blocking submissions

README.md
=> Adding missing items to FieldSubscription docs

README.md, src/index.js.flow, src/types.js.flow
Just a flow type, to enable things to come...
=> Added Decorator type

README.md, src/FinalForm.fieldSubscribing.test.js, src/FinalForm.js, src/index.js, src/index.js.flow, src/structure/getIn.js, src/structure/getIn.test.js, src/types.js.flow
- Added decorators
- Added `getRegisteredFields()` API
- Exported `getIn` and `setIn`
=> Created the concept of a form "decorator"

README.md
=> Fixing typo in Readme.md

src/FinalForm.js, src/FinalForm.test.js, src/FinalForm.validating.test.js
Fixes https://github.com/final-form/react-final-form/issues/49.
=> Added check that a field is registered before setting error

src/FinalForm.js, src/FinalForm.validating.test.js
Fixes https://github.com/final-form/react-final-form-arrays/issues/3.
=> Fixed deep array field-level validation bug

src/structure/setIn.js, src/structure/setIn.test.js
=> Fixed array deletion bug

README.md, src/FinalForm.js, src/FinalForm.validating.test.js, src/publishFieldState.js, src/publishFieldState.test.js, src/types.js.flow
Fixes https://github.com/final-form/react-final-form-arrays/issues/3.
=> Fixed array sync error bug

package.json
Should have been part of #30, oops...
=> Actually expose the TypeScript typings

README.md, src/FinalForm.batching.test.js, src/FinalForm.js, src/types.js.flow
Adds finer control over batching.
=> Finer (more dangerous) batch control

README.md, src/FinalForm.batching.test.js, src/FinalForm.js, src/types.js.flow
Reverts #42.
Changed my mind on this.
=> Revert "Finer (more dangerous) batch control"

README.md, src/FinalForm.fieldSubscribing.test.js, src/FinalForm.js, src/FinalForm.validating.test.js, src/index.d.ts, src/publishFieldState.js, src/publishFieldState.test.js, src/shallowEqual.js, src/types.js.flow
Fixes #37 and https://github.com/final-form/react-final-form/issues/59.
⚠️ BREAKING CHANGE ⚠️
=> Custom isEqual and validateFields field config

README.md, package-lock.json, package.json, src/FinalForm.js, src/FinalForm.submission.test.js, src/index.d.ts, src/types.js.flow
Added `form: FormApi` to params passed to `onSubmit`.
⚠️ BREAKING CHANGE ⚠️
=> Form to on submit (v3)

README.md, src/FinalForm.js, src/FinalForm.submission.test.js, src/fieldSubscriptionItems.js, src/formSubscriptionItems.js, src/index.d.ts, src/publishFieldState.js, src/types.js.flow
Fixes #4.
Fixes #38.
Fixes #48.
=> Added dirtySinceLastSubmit flag for fields and form

README.md, package.json, src/FinalForm.fieldSubscribing.test.js, src/FinalForm.js, src/FinalForm.validating.test.js, src/index.d.ts, src/types.js.flow
To enable a bug fix on 🏁 React Final Form, I've changed how fields register their field-level validation functions. This is a ⚠️ **BREAKING CHANGE** ⚠️.
=> Changed how fields register validators

src/FinalForm.js, src/FinalForm.submission.test.js
=> Made submitFailed true when submit fails due to validation errors

src/structure/setIn.js, src/structure/setIn.test.js
Fixes https://github.com/final-form/react-final-form/issues/133.
=> Allow setting undefined array values

README.md, src/FinalForm.js, src/FinalForm.subscribing.test.js, src/filterFormState.js, src/filterFormState.test.js, src/formSubscriptionItems.js, src/types.js.flow
Fixes https://github.com/final-form/react-final-form/issues/132.
=> Added touched and visited objects to form state

src/types.js.flow
=> Sealed subscription flow types

README.md
Just some documentation fixes.
The description for registerField says it takes a `FieldSubscriber` twice. It should be `FieldSubscriber` and `FieldSubcription` I believe. 
I've updated the link also which seems to work on my fork. 
Let me know if I need to do anything else. Thanks for the great tool!
=> Update RegisterField details and detail link in readme

README.md, src/FinalForm.fieldSubscribing.test.js, src/FinalForm.js, src/index.d.ts, src/types.js.flow
=> Added getFieldState() to form api

src/FinalForm.js, src/FinalForm.subscribing.test.js, src/FinalForm.validating.test.js, src/index.js, src/publishFieldState.js, src/symbols.js
=> Fixed bug where field level validation errors were getting lost

README.md, src/FinalForm.fieldSubscribing.test.js, src/FinalForm.js
Closes #98.
Closes #99.
Thanks for the idea, @quicksnap.
=> Allowed initial values to be passed to reset

src/FinalForm.js, src/FinalForm.submission.test.js, src/types.js.flow
=> Return errors from submit()

src/FinalForm.js, src/FinalForm.validating.test.js
=> Remove field-level error on unregister

src/FinalForm.js, src/FinalForm.submission.test.js
=> Mark all as touched when submission fails with submit errors

src/index.d.ts, src/types.js.flow
#100 didn't properly update the flow and typescript signatures.
=> Fixed type signature for FormApi.reset

README.md, src/FinalForm.js, src/FinalForm.submission.test.js, src/index.d.ts, src/types.js.flow
=> Allowed additional values to be appended on submit

README.md, src/FinalForm.js, src/FinalForm.submission.test.js, src/index.d.ts, src/types.js.flow
Reverts final-form/final-form#115
The more I think about it, the less useful this idea feels.
=> Revert "Allowed additional values to be appended on submit"

src/FinalForm.validating.test.js
Failing test for #121
This test is fixed by #123
=> Test that the form is marked as valid when required fields are completed

src/FinalForm.js
Fix for https://github.com/final-form/final-form/issues/121
Basically just loop through the errors object and find the first defined error.
=> Verify no error is undefined when checking

.babelrc, package-lock.json, package.json, rollup.config.js, tsconfig.json
=> Upgraded deps. BABEL 7!!!

README.md, src/FinalForm.fieldSubscribing.test.js, src/FinalForm.js, src/FinalForm.setConfig.test.js, src/index.d.ts, src/types.js.flow
New flag to delete field values when they are unregistered.
=> Added destroyOnUnregister config flag

src/FinalForm.js, src/FinalForm.submission.test.js, src/FinalForm.validating.test.js
=> Made submitting and validating flags flip to false on Promise rejection

README.md, src/FinalForm.js, src/FinalForm.subscribing.test.js, src/formSubscriptionItems.js, src/types.js.flow
=> Added dirtyFields object to FormState

README.md, src/FinalForm.js
Addresses issue raised here: https://github.com/final-form/react-final-form/issues/310#issuecomment-409239501
=> Ensured calculated form state returned from getState()

rollup.config.js
=> handle node-specific globals in es builds

src/FinalForm.js
This PR fixes a potential time waste for future programmers that accidentally have the following `onSubmit` function:
```js
handleSubmit = (values: object, form: FormApi, callback?: (errors?: object) => void) => {
return new Promise(....);
});
```
The current code first checks if the number of parameters is 3 and then assumes that the onSubmit function uses the callback style. My suggestion is to first check if the function returns a promise and assume Promise style if this is the case. Another solution would be to enhance the documentation and add a warning that Promise-based submit handlers should never have three parameters.
=> Rely less on onSubmit.length to determine callback style

README.md
=> fix typo of strict not equal operator

src/FinalForm.mutators.test.js, src/structure/setIn.js, src/structure/setIn.test.js
Seems to me like a better logic for this use case
=> Remove undefined values rather than setting them to undefined

.travis.yml, README.md, package-lock.json, package.json
=> Upgraded deps and bundle size

README.md, src/FinalForm.creation.test.js, src/FinalForm.fieldSubscribing.test.js, src/FinalForm.js, src/index.d.ts, src/types.js.flow
Fixes https://github.com/final-form/react-final-form/issues/387.
=> Added defaultValue and initialValue options to FieldConfig

src/FinalForm.js, src/FinalForm.submission.test.js
Followup to https://github.com/final-form/react-final-form/pull/433
=> Dont call onSubmit while submitting

src/index.d.ts
this will make the ConfigKey type more robust to future changes
=> dynamically generate ConfigKey using keyof

.travis.yml, README.md, package-lock.json, package.json, src/FinalForm.js, src/FinalForm.submission.test.js, src/index.d.ts, src/types.js.flow
Optional callbacks to fields for pre and post submit.
=> Added beforeSubmit and afterSubmit to FieldConfig

src/FinalForm.js, src/FinalForm.submission.test.js, src/FinalForm.subscribing.test.js
Made field iteration safer and more immune to field unregistration during notifications.
Fixes #26
=> Safe field iteration

README.md, package.json, src/FinalForm.js, src/FinalForm.submission.test.js
=> Throw error if attempt to reset() when submitting

package-lock.json, package.json, rollup.config.js, src/FinalForm.creation.test.js, src/FinalForm.js
Like https://github.com/final-form/react-final-form/pull/532
=> Lookup version at build time

README.md, src/FinalForm.js, src/FinalForm.setConfig.test.js, src/index.d.ts, src/types.js.flow
Gonna be useful for https://github.com/final-form/react-final-form/pull/537.
=> Added destroyOnUnregister getter and setter

src/FinalForm.js, src/FinalForm.submission.test.js
=> Clean submitError & submitErrors when submitting

package.json, src/FinalForm.js, src/FinalForm.submission.test.js
=> Fixed bug in hasAnyError

src/index.d.ts
=> Fixed TS GetFieldValidator

src/FinalForm.js
Array.prototype.find is not supported by IE11 and also seems like Array.prototype.some is more suitable for this case.
=> Better compatibility with IE11

src/FinalForm.js, src/FinalForm.validating.test.js, src/index.d.ts, src/types.js.flow
Greatly simplifies some of the logic on registering a field
=> Fixed bug where changing field-level validation would not update other fields

package.json, src/FinalForm.creation.test.js, src/FinalForm.js
Closes https://github.com/final-form/react-final-form/pull/636.
Fixes https://github.com/final-form/react-final-form/issues/533.
Fixes https://github.com/final-form/react-final-form/issues/536.
=> Only set initial value on field reg if no initial value from form

package.json
https://blog.opencollective.com/beyond-post-install/
=> Use funding field instead of postinstall script

docs/types/FieldState.md
Just a simple documentation fix.
=> docs: fix description of modified to reflect resetFieldState behaviour

docs/types/FieldConfig.md, package.json, src/FinalForm.creation.test.js, src/FinalForm.js, src/index.d.ts, src/types.js.flow
Part of a fix for https://github.com/final-form/react-final-form/issues/751.
=> Added silent flag to allow for silent field registration

src/FinalForm.creation.test.js, src/FinalForm.js
Fixes https://github.com/final-form/react-final-form/issues/768 and https://github.com/final-form/react-final-form/issues/751#issuecomment-606725324.
=> Fixed bug that broke silent registration when using a validator

src/index.d.ts
=> add form.restart types

src/FinalForm.js
Related to https://github.com/final-form/react-final-form/issues/823
=> force field level initialization over form level

src/FinalForm.js, src/FinalForm.mutators.test.js
=> fix a crash when renamed field is unregistered

src/index.d.ts
Added missing method to FormApi.
=> Added restart method to FormApi interface

src/types.js.flow
Fix for issue [840](https://github.com/final-form/react-final-form/issues/840).
=> add missing restart function definition to FormApi

package.json, src/FinalForm.js, src/index.d.test.ts, src/index.d.ts, src/types.js.flow
I tried to clone and npm run precommit after this morning's PR merging. Apparently, no one ran precommit before submitting their PRs. Now it is building for me fine :)
=> fixed build

docs/getting-started.md
Remove the additional curly brace in `docs/getting-started.md`.
=> docs(getting-started): remove additional curly brace

.github/workflows/lock.yml
https://github.com/marketplace/actions/lock-threads
=> Fix lockbot

package.json, src/FinalForm.js, src/FinalForm.validating.test.js
=> Better fix for async error bug

docs/philosophy.md
Removing a duplicate paragraph in the docs
=> Remove docs duplicate

src/index.d.ts
https://github.com/final-form/final-form/issues/459
=> fix /final-form/final-form/issues/457
